const templates = [
  new Set([
  {col: 3, row: 2},
  {col: 3, row: 3},
  {col: 3, row: 4},
  {col: 3, row: 5},
  {col: 3, row: 6},
  {col: 1, row: 3},
  {col: 2, row: 3},
  {col: 4, row: 3},
  {col: 5, row: 3},
  {col: 5, row: 4},
  {col: 4, row: 4},
  {col: 2, row: 4},
  {col: 1, row: 4},
  {col: 2, row: 6},
  {col: 4, row: 6}
]),
new Set([
  {col: 3, row: 2},
  {col: 3, row: 3},
  {col: 3, row: 4},
  {col: 3, row: 5},
  {col: 3, row: 6},
  {col: 1, row: 4},
  {col: 2, row: 4},
  {col: 4, row: 4},
  {col: 5, row: 4},
  {col: 2, row: 3},
  {col: 4, row: 3},
  {col: 4, row: 6},
]),
new Set([
  {col: 5, row: 1},
  {col: 5, row: 2},
  {col: 5, row: 3},
  {col: 5, row: 4},
  {col: 5, row: 5},
  {col: 3, row: 5},
  {col: 7, row: 5},
  {col: 3, row: 4},
  {col: 3, row: 3},
  {col: 4, row: 4},
  {col: 6, row: 3},
  {col: 6, row: 2},
]),
new Set([
  {col: 3, row: 3},
  {col: 4, row: 3},
  {col: 5, row: 3},
  {col: 6, row: 3},
  {col: 7, row: 3},
  {col: 3, row: 5},
  {col: 4, row: 5},
  {col: 5, row: 5},
  {col: 6, row: 5},
  {col: 7, row: 5},
  {col: 5, row: 4},
  {col: 4, row: 4},
  {col: 6, row: 4},
  {col: 3, row: 2},
  {col: 5, row: 2},
  {col: 7, row: 2},
  {col: 7, row: 6},
  {col: 3, row: 6},
]),
new Set([
  {col: 4, row: 2},
  {col: 4, row: 3},
  {col: 3, row: 2},
  {col: 3, row: 3},
  {col: 3, row: 4},
  {col: 3, row: 6},
  {col: 5, row: 2},
  {col: 5, row: 3},
  {col: 5, row: 4},
  {col: 5, row: 6},
  {col: 2, row: 6},
  {col: 6, row: 6},
  {col: 4, row: 5},
]),
];

export default templates